# Generated by Django 4.0.2 on 2022-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritabali', '0002_filter_term_tf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='jumlah_term',
            field=models.IntegerField(null=True),
        ),
    ]
