# Generated by Django 4.0.2 on 2022-03-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritabali', '0005_alter_document_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
