# Generated by Django 4.0.2 on 2022-03-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritabali', '0006_document_fold'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tipe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
